image: "maven:3-openjdk-18-slim"
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
stages:
  - build
  - test
cache:
  paths:
    - .m2/repository/
    - target/
before_script:
  - export PATH="$CI_PROJECT_DIR/global_bin:$CI_PROJECT_DIR/src/main/bin:$CI_PROJECT_DIR/src/test/script:$PATH"
build:
  stage: build
  script:
    - mvn $MAVEN_OPTS clean compile
test:
  stage: test
  dependencies:
    - build
  script:
    - mvn $MAVEN_CLI_OPTS test
  only:
    - master
    - /^feature.*$/
    - /^bug.*$/
    - /^test.*$/
    - /^fix.*$/
    - merge_requests